apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: developer-hub-realm
spec:
  keycloakCRName: keycloak-instance
  realm: 
    realm: "rhdh"
    displayName: "Red Hat Developer Hub Realm"
    enabled: true
    browserFlow: browser
    clients:
      - clientId: rhdh
        name: "rhdh"
        description: "Red Hat Developer Hub Catalog"
        rootUrl: "https://DEVELOPER_HUB_HOSTNAME"
        adminUrl: "https://DEVELOPER_HUB_HOSTNAME"
        baseUrl: "https://DEVELOPER_HUB_HOSTNAME"
        enabled: true
        secret: rhdh-super-secret
        redirectUris:
          - https://DEVELOPER_HUB_HOSTNAME/api/auth/oidc/handler/frame
        webOrigins:
          - "+"
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: true
        publicClient: false
        protocol: openid-connect
    
    users:
      - username: service-account-rhdh
        enabled: true
        serviceAccountClientId: rhdh
        clientRoles:
          realm-management:
            - query-groups
            - view-users
            - query-users
    
      - username: test
        firstName: Developer
        lastName: Hub
        email: test@email.com
        emailVerified: true
        enabled: true
        realmRoles:
          - default-roles-rhdh
        credentials:
          - id: 8d69c1b5-f3a2-4d3f-8a5f-1c18886e83bb
            type: password
            userLabel: My password
            createdDate: 1772050200262
            secretData: '{"value":"NiJ7UXSrTBu2bUUs5yXtyrla1gkb0n4/u4UtkxAadl8=","salt":"bRvNiXZj5h6ldMr36EsSyg==","additionalParameters":{}}'
            credentialData: '{"hashIterations":5,"algorithm":"argon2","additionalParameters":{"hashLength":["32"],"memory":["7168"],"type":["id"],"version":["1.3"],"parallelism":["1"]}}'
