auth:
  session:
    secret: myramdonsessionsecret
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: "${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        prompt: auto
        sessionDuration: { hours: 24 }
        signIn:
          resolvers:
            - resolver: emailLocalPartMatchingUserEntityName
signInPage: oidc
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        realm: ${KEYCLOAK_REALM}
        loginRealm: ${KEYCLOAK_REALM}
        userQuerySize: 100
        groupQuerySize: 100
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 30}
