apiVersion: rhdh.redhat.com/v1alpha4
kind: Backstage
metadata:
  labels:
    app.kubernetes.io/name: backstage
  name: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: rhbk-app-config
    dynamicPluginsConfigMapName: rhbk-dynamic-plugin
    extraEnvs:
      secrets:
      - name: rhbk-secret
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  monitoring:
    enabled: false
